<?php
namespace TADev\Sankhya\Console\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use TADev\Sankhya\Helper\Integration\Authentication;

class Test extends Command
{
    public function __construct(string $name = null)
    {
        parent::__construct($name);
    }

    protected function configure()
    {
        $this->setName('tadev:test')
            ->setDescription('Teste Simples');

        parent::configure();
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
         //$output->Autentication->phpLogin()
        $output->writeln('Teste');
        // parent::execute($input, $output); // TODO: Change the autogenerated stub

    }
}
